# Generated by Django 5.1.7 on 2025-05-09 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_postmedia_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hashtag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trend', to='posts.hashtag')),
                ('posts', models.ManyToManyField(blank=True, related_name='trends', to='posts.post')),
            ],
        ),
    ]
