# Generated by Django 5.1.7 on 2025-05-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_add_default_reactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('post', 'Post'), ('announcement', 'Announcement')], default='post', max_length=20),
        ),
    ]
