# Generated by Django 5.1.7 on 2025-05-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_bio_user_dob_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STAFF', 'Staff'), ('USER', 'User'), ('SUPERUSER', 'Superuser')], default='USER', help_text='Designates the role of this user in the system', max_length=10, verbose_name='Role'),
        ),
    ]
